export const FETCH_COMPANIONS_ACTION = 'actions.companions.FETCH_COMPANIONS_ACTION'
export const FETCH_COMPANIONS_SUCCESS = 'actions.companions.FETCH_COMPANIONS_SUCCESS'
export const FETCH_COMPANIONS_FAILED = 'actions.companions.FETCH_COMPANIONS_FAILED'
